# Generated by Django 3.2.20 on 2023-07-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=50)),
                ('itemPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('itemDesc', models.TextField()),
            ],
        ),
    ]
